spring:
  datasource:
    # https://console.aiven.io/
    url: jdbc:mysql://mysql-{}.{}.aivencloud.com:{}/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_{}
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # ddl-auto: create
      ddl-auto: update
      naming:
        # physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # createdAt -> created_at
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true # 로그로 SQL
    properties:
      hibernate:
        format_sql: true # 로그에 나온 SQL이 줄바꿈 등 포맷팅
  # S3
  # spring:
  cloud:
    aws:
      region:
        # Connection - S3 protocol connection - Region
        static: {}
      credentials:
        # Access key ID
        access-key: {}
        # Secret access key
        secret-key: {}
      s3:
        # Connection - S3 protocol connection - Endpoint
        endpoint: {}
        path-style-access-enabled: true

# @value
aws:
  s3:
    # 생성한 버킷명
    bucket: {}

file:
  storage:
    type: local
    # type: s3