spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      # ddl-auto: none
    # S3
    # spring:
    # https://supabase.com/
    # https://supabase.com/dashboard/sign-in
  cloud:
    aws:
      region:
        # Connection - S3 protocol connection - Region
        static: ${S3_REGION}
      credentials:
        # Access key ID
        access-key: ${S3_ACCESS_KEY}
        # Secret access key
        secret-key: ${S3_SECRET_KEY}
      S3:
        # Connection - S3 protocol connection - Endpoint
        endpoint: ${S3_ACCESS_ENDPOINT}
        path-style-access-enabled: true

# @value
aws:
  s3:
    # 생성한 버킷명
    bucket: ${S3_BUCKET_NAME}

file:
  storage:
    # type: local
    type: s3