server:
  port: 8080

spring:
  application:
    name: 251212_upload-exception
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: dev

# 파일 업로드 관련 설정
  servlet:
    multipart:
      enabled: true # 업로드 기능 활성화 -> mvc
      # 개별 파일 최대 크기
      max-file-size: 10MB
      # 전체 요청 최대 크기
      max-request-size: 30MB
      # 별도 저장 없이 메모리에서 처리
      file-size-threshold: 2KB

# 경로
file: # 밑 폴더는 자동으로 생성
  upload-dir: uploads